from mongoengine import Document, StringField, IntField

class Prompt(Document):
    # # id's are automatically generated by MongoDB, but we can add them if you want
    # prompt_id = IntField(required=True, unique=True, )
    prompt_content = StringField(required=True)
    prompt_category = StringField(required=True)
    prompt_icon = StringField()  # Assuming icon is stored as a URL or file path
    
    def to_json(self):
        return {
            "prompt_id": self.prompt_id,
            "prompt_content": self.prompt_content,
            "prompt_category": self.prompt_category,
            "prompt_icon": self.prompt_icon
        }  

    meta = {'collection': 'prompts'}
